#Dev version to grab files from my local machine

version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    build: /home/sapporo/Coding/DeepLearning/GardenApp/client-app-dev # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forewarding
    volumes:
      - /home/sapporo/Coding/DeepLearning/GardenApp/client-app:/usr/src/garden-app-dev

  express-ts: #name of the second service
    build: express-ts-server # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    links:
      - database # link this service to the database service
    volumes:
      - /home/sapporo/Coding/DeepLearning/GardenApp/express-ts-server:/usr/src/express-ts-app

  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding
    volumes: 
      - /home/sapporo/Coding/DeepLearning/GardenApp/database:/data/db